name: specs

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate service and link specs
        run: bash postgresql-flexible-server/examples/validate-specs.sh
      - name: Run unit tests
        run: bash postgresql-flexible-server/examples/run-all-tests.sh
